// default package
// Generated 2017-10-13 16:07:10 by Hibernate Tools 5.0.6.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TForum generated by hbm2java
 */
@Entity
@Table(name="t_forum"
    ,catalog="sampledb"
)
public class TForum  implements java.io.Serializable {


     private Integer forumId;
     private String forumName;
     private String forumDesc;

    public TForum() {
    }

	
    public TForum(String forumName) {
        this.forumName = forumName;
    }
    public TForum(String forumName, String forumDesc) {
       this.forumName = forumName;
       this.forumDesc = forumDesc;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="forum_id", unique=true, nullable=false)
    public Integer getForumId() {
        return this.forumId;
    }
    
    public void setForumId(Integer forumId) {
        this.forumId = forumId;
    }

    
    @Column(name="forum_name", nullable=false, length=150)
    public String getForumName() {
        return this.forumName;
    }
    
    public void setForumName(String forumName) {
        this.forumName = forumName;
    }

    
    @Column(name="forum_desc")
    public String getForumDesc() {
        return this.forumDesc;
    }
    
    public void setForumDesc(String forumDesc) {
        this.forumDesc = forumDesc;
    }




}


