// default package
// Generated 2017-10-13 16:07:10 by Hibernate Tools 5.0.6.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TPostId generated by hbm2java
 */
@Entity
@Table(name="t_post_id"
    ,catalog="sampledb"
)
public class TPostId  implements java.io.Serializable {


     private Integer sequenceId;

    public TPostId() {
    }

    public TPostId(Integer sequenceId) {
       this.sequenceId = sequenceId;
    }
   
     @Id 

    
    @Column(name="sequence_id")
    public Integer getSequenceId() {
        return this.sequenceId;
    }
    
    public void setSequenceId(Integer sequenceId) {
        this.sequenceId = sequenceId;
    }




}


