// default package
// Generated 2017-10-13 16:07:10 by Hibernate Tools 5.0.6.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TPost generated by hbm2java
 */
@Entity
@Table(name="t_post"
    ,catalog="sampledb"
)
public class TPost  implements java.io.Serializable {


     private int postId;
     private int topicId;
     private int forumId;
     private int userId;
     private String postText;
     private byte[] postAttach;
     private Date postTime;

    public TPost() {
    }

	
    public TPost(int postId, int topicId, int forumId, int userId) {
        this.postId = postId;
        this.topicId = topicId;
        this.forumId = forumId;
        this.userId = userId;
    }
    public TPost(int postId, int topicId, int forumId, int userId, String postText, byte[] postAttach, Date postTime) {
       this.postId = postId;
       this.topicId = topicId;
       this.forumId = forumId;
       this.userId = userId;
       this.postText = postText;
       this.postAttach = postAttach;
       this.postTime = postTime;
    }
   
     @Id 

    
    @Column(name="post_id", unique=true, nullable=false)
    public int getPostId() {
        return this.postId;
    }
    
    public void setPostId(int postId) {
        this.postId = postId;
    }

    
    @Column(name="topic_id", nullable=false)
    public int getTopicId() {
        return this.topicId;
    }
    
    public void setTopicId(int topicId) {
        this.topicId = topicId;
    }

    
    @Column(name="forum_id", nullable=false)
    public int getForumId() {
        return this.forumId;
    }
    
    public void setForumId(int forumId) {
        this.forumId = forumId;
    }

    
    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }

    
    @Column(name="post_text", length=65535)
    public String getPostText() {
        return this.postText;
    }
    
    public void setPostText(String postText) {
        this.postText = postText;
    }

    
    @Column(name="post_attach")
    public byte[] getPostAttach() {
        return this.postAttach;
    }
    
    public void setPostAttach(byte[] postAttach) {
        this.postAttach = postAttach;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="post_time", length=19)
    public Date getPostTime() {
        return this.postTime;
    }
    
    public void setPostTime(Date postTime) {
        this.postTime = postTime;
    }




}


