// default package
// Generated 2017-10-13 16:07:10 by Hibernate Tools 5.0.6.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TTopic generated by hbm2java
 */
@Entity
@Table(name="t_topic"
    ,catalog="sampledb"
)
public class TTopic  implements java.io.Serializable {


     private Integer topicId;
     private int forumId;
     private String topicTitle;
     private int userId;
     private Date topicTime;
     private Integer topicViews;
     private Integer topicReplies;

    public TTopic() {
    }

	
    public TTopic(int forumId, String topicTitle, int userId) {
        this.forumId = forumId;
        this.topicTitle = topicTitle;
        this.userId = userId;
    }
    public TTopic(int forumId, String topicTitle, int userId, Date topicTime, Integer topicViews, Integer topicReplies) {
       this.forumId = forumId;
       this.topicTitle = topicTitle;
       this.userId = userId;
       this.topicTime = topicTime;
       this.topicViews = topicViews;
       this.topicReplies = topicReplies;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="topic_id", unique=true, nullable=false)
    public Integer getTopicId() {
        return this.topicId;
    }
    
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }

    
    @Column(name="forum_id", nullable=false)
    public int getForumId() {
        return this.forumId;
    }
    
    public void setForumId(int forumId) {
        this.forumId = forumId;
    }

    
    @Column(name="topic_title", nullable=false, length=100)
    public String getTopicTitle() {
        return this.topicTitle;
    }
    
    public void setTopicTitle(String topicTitle) {
        this.topicTitle = topicTitle;
    }

    
    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="topic_time", length=19)
    public Date getTopicTime() {
        return this.topicTime;
    }
    
    public void setTopicTime(Date topicTime) {
        this.topicTime = topicTime;
    }

    
    @Column(name="topic_views")
    public Integer getTopicViews() {
        return this.topicViews;
    }
    
    public void setTopicViews(Integer topicViews) {
        this.topicViews = topicViews;
    }

    
    @Column(name="topic_replies")
    public Integer getTopicReplies() {
        return this.topicReplies;
    }
    
    public void setTopicReplies(Integer topicReplies) {
        this.topicReplies = topicReplies;
    }




}


